# http://docs.travis-ci.com/user/languages/python/

dist: xenial

language: python
python:
    - 2.7
    - pypy
    - 3.6

before_install:
    - sudo add-apt-repository ppa:libreoffice/libreoffice-6-1 -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq libreoffice

script:
    python setup.py test

sudo: required
